apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtest
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: local-path
  hostPath:
    path: /tmp/pv