apiVersion: apps/v1
kind: Deployment
metadata:
  name: karina
  namespace: system
  labels:
    control-plane: karina-operator
spec:
  selector:
    matchLabels:
      control-plane: karina-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: karina-operator
    spec:
      serviceAccountName: karina
      containers:
        - command:
            - /bin/karina
          args:
            - operator
            - --enable-leader-election
            - --log-level=debug
          image: docker.io/flanksource/karina:latest
          imagePullPolicy: IfNotPresent
          name: karina-operator
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
